apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-videoanalytics
          image: docker.io/checkpoint5/django:latest
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: postgres-storage
            - mountPath: /dev/video0
              name: camera
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_HOST
              value: 'postgres-statefulset-0.postgres-service.default.svc.cluster.local'
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_DB
              value: my_database
            - name: POSTGRES_USER
              value: my_username
            - name: POSTGRES_PASSWORD
              value: my_password
            - name: APP_ENV
              value: k8s
          securityContext:
            privileged: true
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc-postgres-statefulset-0
        - name: camera
          hostPath:
            path: /dev/video0
  selector:
    matchLabels:
      app: django-app
